spring:
  application:
    name: department-service
  config:
    import: "configserver:http://localhost:8088"
  cloud:
      config:
          server:
              git:
               default-label: main


